const { Follow } = require("../models");

const followSeed = async () => {
    const followData = [
        { folllowingUserId: 1, followerUserId: 1 },
        { folllowingUserId: 2, followerUserId: 2 },
        { folllowingUserId: 3, followerUserId: 3 },
        { folllowingUserId: 4, followerUserId: 4 },
        { folllowingUserId: 5, followerUserId: 5 },
        { folllowingUserId: 6, followerUserId: 6 },
        { folllowingUserId: 7, followerUserId: 7 },
        { folllowingUserId: 8, followerUserId: 8 },
        { folllowingUserId: 9, followerUserId: 9 },
        { folllowingUserId: 10, followerUserId: 10 },
        { folllowingUserId: 11, followerUserId: 11 },
        { folllowingUserId: 12, followerUserId: 12 },
        { folllowingUserId: 13, followerUserId: 13 },
        { folllowingUserId: 14, followerUserId: 14 },
        { folllowingUserId: 15, followerUserId: 15 },
        { folllowingUserId: 16, followerUserId: 16 },
        { folllowingUserId: 17, followerUserId: 17 },
        { folllowingUserId: 18, followerUserId: 18 },
        { folllowingUserId: 19, followerUserId: 19 },
        { folllowingUserId: 20, followerUserId: 20 },
        { folllowingUserId: 21, followerUserId: 21 },
        { folllowingUserId: 22, followerUserId: 22 },
        { folllowingUserId: 23, followerUserId: 23 },
        { folllowingUserId: 24, followerUserId: 24 },
        { folllowingUserId: 25, followerUserId: 25 },
        { folllowingUserId: 26, followerUserId: 26 },
        { folllowingUserId: 27, followerUserId: 27 },
        { folllowingUserId: 28, followerUserId: 28 },
        { folllowingUserId: 29, followerUserId: 29 },
        { folllowingUserId: 30, followerUserId: 30 },
        { folllowingUserId: 31, followerUserId: 31 },
        { folllowingUserId: 32, followerUserId: 32 },
        { folllowingUserId: 33, followerUserId: 33 },
        { folllowingUserId: 34, followerUserId: 34 },
        { folllowingUserId: 35, followerUserId: 35 },
        { folllowingUserId: 36, followerUserId: 36 },
        { folllowingUserId: 37, followerUserId: 37 },
        { folllowingUserId: 38, followerUserId: 38 },
        { folllowingUserId: 39, followerUserId: 39 },
        { folllowingUserId: 40, followerUserId: 40 },
        { folllowingUserId: 41, followerUserId: 41 },
        { folllowingUserId: 42, followerUserId: 42 },
        { folllowingUserId: 43, followerUserId: 43 },
        { folllowingUserId: 44, followerUserId: 44 },
        { folllowingUserId: 45, followerUserId: 45 },
        { folllowingUserId: 46, followerUserId: 46 },
        { folllowingUserId: 47, followerUserId: 47 },
        { folllowingUserId: 48, followerUserId: 48 },
        { folllowingUserId: 49, followerUserId: 49 },
        { folllowingUserId: 50, followerUserId: 50 },
        { folllowingUserId: 51, followerUserId: 51 },
        { folllowingUserId: 52, followerUserId: 52 },
        { folllowingUserId: 53, followerUserId: 53 },
        { folllowingUserId: 54, followerUserId: 54 },
        { folllowingUserId: 55, followerUserId: 55 },
        { folllowingUserId: 56, followerUserId: 56 },
        { folllowingUserId: 57, followerUserId: 57 },
        { folllowingUserId: 58, followerUserId: 58 },
        { folllowingUserId: 59, followerUserId: 59 },
        { folllowingUserId: 60, followerUserId: 60 },
        { folllowingUserId: 61, followerUserId: 61 },
        { folllowingUserId: 62, followerUserId: 62 },
        { folllowingUserId: 63, followerUserId: 63 },
        { folllowingUserId: 64, followerUserId: 64 },
        { folllowingUserId: 65, followerUserId: 65 },
        { folllowingUserId: 66, followerUserId: 66 },
        { folllowingUserId: 67, followerUserId: 67 },
        { folllowingUserId: 68, followerUserId: 68 },
        { folllowingUserId: 69, followerUserId: 69 },
        { folllowingUserId: 70, followerUserId: 70 },
        { folllowingUserId: 71, followerUserId: 71 },
        { folllowingUserId: 72, followerUserId: 72 },
        { folllowingUserId: 73, followerUserId: 73 },
        { folllowingUserId: 74, followerUserId: 74 },
        { folllowingUserId: 75, followerUserId: 75 },
        { folllowingUserId: 76, followerUserId: 76 },
        { folllowingUserId: 77, followerUserId: 77 },
        { folllowingUserId: 78, followerUserId: 78 },
        { folllowingUserId: 79, followerUserId: 79 },
        { folllowingUserId: 80, followerUserId: 80 },
        { folllowingUserId: 81, followerUserId: 81 },
        { folllowingUserId: 82, followerUserId: 82 },
        { folllowingUserId: 83, followerUserId: 83 },
        { folllowingUserId: 84, followerUserId: 84 },
        { folllowingUserId: 85, followerUserId: 85 },
        { folllowingUserId: 86, followerUserId: 86 },
        { folllowingUserId: 87, followerUserId: 87 },
        { folllowingUserId: 88, followerUserId: 88 },
        { folllowingUserId: 89, followerUserId: 89 },
        { folllowingUserId: 90, followerUserId: 90 },
        { folllowingUserId: 91, followerUserId: 91 },
        { folllowingUserId: 92, followerUserId: 92 },
        { folllowingUserId: 93, followerUserId: 93 },
        { folllowingUserId: 94, followerUserId: 94 },
        { folllowingUserId: 95, followerUserId: 95 },
        { folllowingUserId: 96, followerUserId: 96 },
        { folllowingUserId: 97, followerUserId: 97 },
        { folllowingUserId: 98, followerUserId: 98 },
        { folllowingUserId: 99, followerUserId: 99 },
        { folllowingUserId: 100, followerUserId: 100 },
    ];

    let res = await Follow.bulkCreate(followData);
    // console.log(res);
    // process.exit(0);
};
// userSeed();

module.exports = followSeed;
